### ISSUE TITLE
Error in MortgageController.cs, exception was throw.

### ISSUE THREAD

**Issue by Eliaxs1900** [EditionsENI/mortgage#3]
I pulled this repository, following the steps of page 344-346 i received this error:

> Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLNNMLQLRAUU", Request id "0HLNNMLQLRAUU:00000001": An unhandled exception was thrown by the application.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: count
   at System.Linq.Enumerable.Range(Int32 start, Int32 count)
   at Optimizer.MortgageController.GetBestRepaymentDate(Decimal AmountRepaid, Decimal ReplacementFixRate, Mortgage m) in /app/MortgageController.cs:line 18
   at lambda_method(Closure , Object , Object[] )

**Comment by jp-gouigoux** [comment]
Hello,

My guess is that you have used values for the dates of repayment that do not correspond to a realistic situation. Since the repayment will be calculated at the current month, the end date of the mortgage (begin date + length) has to be in the future when you click on the button. Please tell me if adjusting this works for you.

JP
